In [1]:
#importing all the required libraries
import pandas as pd
import numpy as np
import sklearn as sk
import pickle
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
df = pd.read_csv('deceptive-opinion.csv')

In [12]:
df.head()

DOC_ID       LABEL  RATING VERIFIED_PURCHASE PRODUCT_CATEGORY  PRODUCT_ID  \
0       1  __label1__       4                 N               PC  B00008NG7N   
1       2  __label1__       4                 Y         Wireless  B00LH0Y3NM   
2       3  __label1__       3                 N             Baby  B000I5UZ1Q   
3       4  __label1__       4                 N  Office Products  B003822IRA   
4       5  __label1__       4                 N           Beauty  B00PWSAXAM   

                                       PRODUCT_TITLE  \
0        Targus PAUK10U Ultra Mini USB Keypad, Black   
1  Note 3 Battery : Stalion Strength Replacement ...   
2       Fisher-Price Papasan Cradle Swing, Starlight   
3  Casio MS-80B Standard Function Desktop Calculator   
4  Shine Whitening - Zero Peroxide Teeth Whitenin...   

               REVIEW_TITLE                                        REVIEW_TEXT  
0                    useful  When least you think so, this product will sav...  
1     New era for batteries  Lithium batteries are something new introduced...  
2  doesn't swing very well.  I purchased this swing for my baby. She is 6 m...  
3          Great computing!  I was looking for an inexpensive desk calcolat...  
4     Only use twice a week  I only use it twice a week and the results are...

In [13]:
df.tail()

DOC_ID       LABEL  RATING VERIFIED_PURCHASE PRODUCT_CATEGORY  \
20995   20996  __label2__       4                 Y            Shoes   
20996   20997  __label2__       4                 Y            Shoes   
20997   20998  __label2__       5                 Y            Shoes   
20998   20999  __label2__       5                 Y            Shoes   
20999   21000  __label2__       4                 Y            Shoes   

       PRODUCT_ID                                      PRODUCT_TITLE  \
20995  B00BXYM8T8  Madden Girl Women's Gettaw Pump,Red Patent,7.5...   
20996  B0014C2ORK  crocs Unisex Classic Clog,Khaki,6 US Men's / 8...   
20997  B000EX8CCQ  Minnetonka Men's 703 Leather Laced Softsole Mo...   
20998  B00748YHVE    Ariat Womens Unbridled Fatbaby 9 B Powder Brown   
20999  B00A46KTLU  VIBRAM FIVEFINGERS SPEED XC MENS HIKING SHOES,...   

                                            REVIEW_TITLE  \
20995                               wide width is great!   
20996                                        Love crocs!   
20997  I love moccasins This fit like it was custom m...   
20998        This fit well, comfortable, best investment   
20999             Love these shoes, except for the laces   

                                             REVIEW_TEXT  
20995  I bought these for work.  I have high arches, ...  
20996  Crocs are one of only two brands of shoes that...  
20997  I love moccasins  This fit like it was custom ...  
20998  I wish these were a little more durable. I got...  
20999  I've been looking for a replacement for my bel...

In [14]:
#Extracting only the requireed features
df1 = df[['deceptive', 'text']]
df1

REVIEW_TITLE  \
0                                                 useful   
1                                  New era for batteries   
2                               doesn't swing very well.   
3                                       Great computing!   
4                                  Only use twice a week   
...                                                  ...   
20995                               wide width is great!   
20996                                        Love crocs!   
20997  I love moccasins This fit like it was custom m...   
20998        This fit well, comfortable, best investment   
20999             Love these shoes, except for the laces   

                                             REVIEW_TEXT  
0      When least you think so, this product will sav...  
1      Lithium batteries are something new introduced...  
2      I purchased this swing for my baby. She is 6 m...  
3      I was looking for an inexpensive desk calcolat...  
4      I only use it twice a week and the results are...  
...                                                  ...  
20995  I bought these for work.  I have high arches, ...  
20996  Crocs are one of only two brands of shoes that...  
20997  I love moccasins  This fit like it was custom ...  
20998  I wish these were a little more durable. I got...  
20999  I've been looking for a replacement for my bel...  

[21000 rows x 2 columns]

In [152]:
#filling the categorical variable deceptive with 0 for fake review and 1 for real review
df1.loc[df1['deceptive'] == 'deceptive', 'deceptive'] = 0
df1.loc[df1['deceptive'] == 'truthful', 'deceptive'] = 1

In [153]:
#Printing Dataframe1
df1

deceptive                                               text
0            1  We stayed for a one night getaway with family ...
1            1  Triple A rate with upgrade to view room was le...
2            1  This comes a little late as I'm finally catchi...
3            1  The Omni Chicago really delivers on all fronts...
4            1  I asked for a high floor away from the elevato...
...        ...                                                ...
1595         0  Problems started when I booked the InterContin...
1596         0  The Amalfi Hotel has a beautiful website and i...
1597         0  The Intercontinental Chicago Magnificent Mile ...
1598         0  The Palmer House Hilton, while it looks good i...
1599         0  As a former Chicagoan, I'm appalled at the Ama...

[1600 rows x 2 columns]

In [154]:
#Taking the input and output features seperately
X = df1['text']
Y = np.asarray(df1['deceptive'], dtype = int)

In [155]:
#importing MultinomialNB
from sklearn.naive_bayes import MultinomialNB, GaussianNB

In [156]:
#splitting the data into training and testing set  with test size is 30%
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=109) # 70% training and 30% test

In [157]:
X_test

1063    We stayed at the Ritz Carlton two weeks prior,...
21      We went to Chicago to see an exhibit at the Ar...
1480    I recently stayed in The James Hotel in Chicag...
1215    Hyatt Regency Hotel: Good ole Downtown, Chicag...
459     Me and my husband got married here. We loved t...
                              ...                        
133     Perfect location, clean and courteous staff al...
1252    If you want a 5-star hotel with 1-star service...
254     We had our hotel reservations at another hotel...
386     We became an Ambassador member just before spe...
1240    My experience as Fairmont Chicago Millennium P...
Name: text, Length: 480, dtype: object

In [158]:
y_test

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [159]:
nb = MultinomialNB()

In [160]:
#Converting the review (text feature) to numerical features
cv = CountVectorizer()
x = cv.fit_transform(X_train)
y = cv.transform(X_test)

In [161]:
# Fitting the model
nb.fit(x, y_train)
pickle.dump(nb,open('model.pkl','wb'))
model=pickle.load(open('model.pkl','rb'))

In [162]:
nb.predict(y)

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [187]:
# Training Accuracy
nb.score(x, y_train)

0.9714285714285714

In [164]:
# Testing Accuracy
nb.score(y, y_test)

0.85625

In [165]:
# Implementing with pywedge
import pywedge as pw 

In [166]:
#blm = pw.baseline_model(x, y_train)

In [167]:
#blm.classification_summary()

<h3> Implementing with the SVM </h3>

In [168]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

In [169]:
#Train the model using the training sets
clf.fit(x, y_train)

KeyError: 'print_changed_only'

In [44]:
#Predict the response for test dataset
y_pred = clf.predict(y)
y_pred

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [46]:
clf.score(x, y_train) #Training accuracy

1.0

In [47]:
clf.score(y, y_test)

0.8166666666666667